# version: "3.8"
# user-service
# services:
#   server:
#     build:
#       context: .
#     environment:
#       NODE_ENV: production
#     ports:
#       - 3000:3000
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  user-service:
    build:
      context: ./services/user-service
      # dockerfile: Dockerfile
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: ./services/user-service
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    command: npm run dev
    # volumes:
    #   - ./services/user-service:/app
    #   - /app/node_modules  # Để tránh ghi đè thư mục node_modules trong container
    ports:
      - "3000:3000"
    env_file:
      - ./services/user-service/.env
